require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DailypostsController do

  # This should return the minimal set of attributes required to create a valid
  # Dailypost. As you add validations to Dailypost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "girl_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DailypostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dailyposts as @dailyposts" do
      dailypost = Dailypost.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dailyposts).should eq([dailypost])
    end
  end

  describe "GET show" do
    it "assigns the requested dailypost as @dailypost" do
      dailypost = Dailypost.create! valid_attributes
      get :show, {:id => dailypost.to_param}, valid_session
      assigns(:dailypost).should eq(dailypost)
    end
  end

  describe "GET new" do
    it "assigns a new dailypost as @dailypost" do
      get :new, {}, valid_session
      assigns(:dailypost).should be_a_new(Dailypost)
    end
  end

  describe "GET edit" do
    it "assigns the requested dailypost as @dailypost" do
      dailypost = Dailypost.create! valid_attributes
      get :edit, {:id => dailypost.to_param}, valid_session
      assigns(:dailypost).should eq(dailypost)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dailypost" do
        expect {
          post :create, {:dailypost => valid_attributes}, valid_session
        }.to change(Dailypost, :count).by(1)
      end

      it "assigns a newly created dailypost as @dailypost" do
        post :create, {:dailypost => valid_attributes}, valid_session
        assigns(:dailypost).should be_a(Dailypost)
        assigns(:dailypost).should be_persisted
      end

      it "redirects to the created dailypost" do
        post :create, {:dailypost => valid_attributes}, valid_session
        response.should redirect_to(Dailypost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dailypost as @dailypost" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dailypost.any_instance.stub(:save).and_return(false)
        post :create, {:dailypost => { "girl_id" => "invalid value" }}, valid_session
        assigns(:dailypost).should be_a_new(Dailypost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dailypost.any_instance.stub(:save).and_return(false)
        post :create, {:dailypost => { "girl_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dailypost" do
        dailypost = Dailypost.create! valid_attributes
        # Assuming there are no other dailyposts in the database, this
        # specifies that the Dailypost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dailypost.any_instance.should_receive(:update_attributes).with({ "girl_id" => "1" })
        put :update, {:id => dailypost.to_param, :dailypost => { "girl_id" => "1" }}, valid_session
      end

      it "assigns the requested dailypost as @dailypost" do
        dailypost = Dailypost.create! valid_attributes
        put :update, {:id => dailypost.to_param, :dailypost => valid_attributes}, valid_session
        assigns(:dailypost).should eq(dailypost)
      end

      it "redirects to the dailypost" do
        dailypost = Dailypost.create! valid_attributes
        put :update, {:id => dailypost.to_param, :dailypost => valid_attributes}, valid_session
        response.should redirect_to(dailypost)
      end
    end

    describe "with invalid params" do
      it "assigns the dailypost as @dailypost" do
        dailypost = Dailypost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dailypost.any_instance.stub(:save).and_return(false)
        put :update, {:id => dailypost.to_param, :dailypost => { "girl_id" => "invalid value" }}, valid_session
        assigns(:dailypost).should eq(dailypost)
      end

      it "re-renders the 'edit' template" do
        dailypost = Dailypost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dailypost.any_instance.stub(:save).and_return(false)
        put :update, {:id => dailypost.to_param, :dailypost => { "girl_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dailypost" do
      dailypost = Dailypost.create! valid_attributes
      expect {
        delete :destroy, {:id => dailypost.to_param}, valid_session
      }.to change(Dailypost, :count).by(-1)
    end

    it "redirects to the dailyposts list" do
      dailypost = Dailypost.create! valid_attributes
      delete :destroy, {:id => dailypost.to_param}, valid_session
      response.should redirect_to(dailyposts_url)
    end
  end

end
